config/routes.rb
Eventos::Application.routes.draw do
  match '/auth/:provider/callback' => 'authentications#create'
  match 'authentications/destroy' => 'authentications#destroy', :method => :delete, :as => :logout
  
  root :to => 'pages#index'
  
  post "event" => "pages#event", :as => :event
  get "terms" => "pages#terms", :as => :terms
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
  
  attr_accessible :create, :destroy, :index, :provider, :uid, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authentications
  
  attr_accessible :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authentications_controller.rb
# encoding: UTF-8
class AuthenticationsController < ApplicationController
  def create
    auth = request.env['omniauth.auth']
    
    session[:facebook] = {}
    session[:facebook][:access_token] = auth.credentials.token
    session[:facebook][:provider] = auth['provider']
    session[:facebook][:uid] = auth['uid']
    session[:facebook][:name] = auth['info']['first_name']
    flash[:notice] = "Autenticação realizada com sucesso!"
    redirect_to root_url
  end

  def destroy
    session[:facebook] = nil
    flash[:notice] = "Successfully destroyed authentication."
    redirect_to root_url
  end
end

app/controllers/pages_controller.rb
# encoding: UTF-8
class PagesController < ApplicationController
  
  def event
    redirect_to root_url unless session[:facebook].present?
    
    arr = params[:event].split("/")
    id = arr[arr.find_index("events") + 1]
    @event = FbGraph::Event.fetch(id)
    ids = @event.attending(:access_token => session[:facebook][:access_token]).map { |u| u.identifier }
    
    @users = HTTParty.get("http://graph.facebook.com/?ids=#{ids.join(",")}").parsed_response
    @males   = @users.values.select { |user| user["gender"] == "male"   }.flatten
    @females = @users.values.select { |user| user["gender"] == "female" }.flatten
  rescue FbGraph::NotFound
    redirect_to root_path, :message => "Não é possível verificar eventos privados ou evento não existe..."
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/authentications/_form.html.erb
<%= form_for(@authentication) do |f| %>
  <% if @authentication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@authentication.errors.count, "error") %> prohibited this authentication from being saved:</h2>

      <ul>
      <% @authentication.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :provider %><br />
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :uid %><br />
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :index %><br />
    <%= f.text_field :index %>
  </div>
  <div class="field">
    <%= f.label :create %><br />
    <%= f.text_field :create %>
  </div>
  <div class="field">
    <%= f.label :destroy %><br />
    <%= f.text_field :destroy %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authentications/edit.html.erb
<h1>Editing authentication</h1>

<%= render 'form' %>

<%= link_to 'Show', @authentication %> |
<%= link_to 'Back', authentications_path %>

app/views/authentications/index.html.erb
<h1>Listing authentications</h1>

<table>
  <tr>
    <th>User</th>
    <th>Provider</th>
    <th>Uid</th>
    <th>Index</th>
    <th>Create</th>
    <th>Destroy</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authentications.each do |authentication| %>
  <tr>
    <td><%= authentication.user_id %></td>
    <td><%= authentication.provider %></td>
    <td><%= authentication.uid %></td>
    <td><%= authentication.index %></td>
    <td><%= authentication.create %></td>
    <td><%= authentication.destroy %></td>
    <td><%= link_to 'Show', authentication %></td>
    <td><%= link_to 'Edit', edit_authentication_path(authentication) %></td>
    <td><%= link_to 'Destroy', authentication, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Authentication', new_authentication_path %>

app/views/authentications/new.html.erb
<h1>New authentication</h1>

<%= render 'form' %>

<%= link_to 'Back', authentications_path %>

app/views/authentications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @authentication.user_id %>
</p>

<p>
  <b>Provider:</b>
  <%= @authentication.provider %>
</p>

<p>
  <b>Uid:</b>
  <%= @authentication.uid %>
</p>

<p>
  <b>Index:</b>
  <%= @authentication.index %>
</p>

<p>
  <b>Create:</b>
  <%= @authentication.create %>
</p>

<p>
  <b>Destroy:</b>
  <%= @authentication.destroy %>
</p>


<%= link_to 'Edit', edit_authentication_path(@authentication) %> |
<%= link_to 'Back', authentications_path %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <%= render :partial => "layouts/social_plugins" %>
  <%= render :partial => "layouts/footer_menu" %>  
</div>

app/views/layouts/_footer_menu.html.erb
<ul class="footer-links">
  <li>Eventualize.se 2012.</li>
  <li><%= link_to "Meganti", "http://meganti.com.br", :target => "_blank" %></li>
  <li><%= link_to "Termos de serviço", terms_path %></li>
  <li><%= mail_to "contato@meganti.com.br", "Contato", :subject => "Eventualize.se - ", :target => "_blank" %></li>
</ul>

app/views/layouts/_header.html.erb
<div class="header">
	<h1><%= link_to(image_tag('logo-eventualize.png', :alt => "Eventualize.se"), root_path) %></h1>
</div>

app/views/layouts/_social_plugins.html.erb
<div class="social">
  <div class="button tw">
    <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.eventualize.se" data-via="eventualizese" data-count="none">Tweet</a>          
  </div>
  <div class="button g+">
    <g:plusone size="medium" href="<%= root_path %>" annotation="none"></g:plusone>
  </div>
  <div class="button fb">
    <div class="fb-like" data-href="https://www.eventualize.se" data-send="false" data-layout="button_count" data-width="90" data-show-faces="false"></div>
  </div>
</div>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

<script type="text/javascript">
  window.___gcfg = {lang: 'pt-BR'};
  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=259846450722130";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

  <head>

    <title>Eventualize.se</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

  </head>

  <body>
    
    <%= render :partial => "layouts/header" %>
  
    <%= yield %>
    
    <%= render :partial => "layouts/footer" %>

  </body>

</html>

app/views/pages/event.html.erb
<div class="event">
	
	<div class="eventinfo">
		<div class="eventinfo__leftcolumn">
			<%= image_tag @event.picture, :alt => @event.name, :class => 'eventinfo__image' %>
			<p class="eventinfo__eventdate"><%= @event.start_time.strftime("%d/%m") %></p>
			<p class="eventinfo__eventtime"><%= @event.start_time.strftime("%H:%M") %></p>
		</div>
		<div class="eventinfo__rightcolumn">
			<h2 class="eventinfo__eventname"><%= @event.name %></h2>
			<h3 class="eventinfo__ownername"><span>by</span> <%= @event.owner.name %></h3>
			<p class="eventinfo__description"><%= @event.description %></p>
			<div class="eventinfo__people">
				<p class="eventinfo__men"><%= @males.size %></p>
				<p class="eventinfo__women"><%= @females.size %></p>
			</div>
		</div>
	</div>
	
	<br />
	<br />
	
</div>

<!--
<h3>Homens:</h3>
<% @males.each do |user| %>
  <%= link_to user["name"], user["link"] %> <br>
<% end %>
<br><br>
<h3>Mulheres</h3>
<% @females.each do |user| %>
  <%= link_to user["name"], user["link"] %> <br>
<% end %>
-->

app/views/pages/index.html.erb
<div class="main">

	<% if session[:facebook].present? %>

	  <p class="userinfo">
			Você está logado como <span class="userinfo__username"><%= session[:facebook][:name] %></span>
		</p>

		<p class="userlogout">
	  	<%= link_to "Deslogar", logout_path, :method => :delete, :class => "userlogout__button" %>
		</p>
		
		<div class="start">

			<h2 class="introduction">
				Copie a URL do evento que você deseja obter as informações e cole-a no campo abaixo.
			</h2>
      
      <%= form_tag event_path, method: :post, class: :searchevent do %>
        <%= text_field_tag :event, "", class: :searchevent__input, placeholder: "Cole a URL do evento aqui" %>
        <%= submit_tag "Ok", class: :searchevent__submit %>
      <% end %>
	
		</div>

	<% else %>

		<div class="start">

			<h2 class="introduction">
				Descubra quantos homens e mulheres vão estar presentes nos seus eventos do Facebook conectando-se abaixo.
			</h2>

			<a href="/auth/facebook" class="fbconnect">
				<span class="fbconnect__icon"><img src="<%= image_path "icon-fbconnect.png" %>" alt="Facebook connect" /></span><span class="fbconnect__text">Conecte-se</span>
			</a>
	
		</div>

	<% end %>

</div>

app/views/pages/terms.html.erb
<div class="terms">
  <h1>Termo de Responsabilidade do site http://eventualize.se</h1>
  <br />

  <h2>Sobre a utilização deste site</h2>
  <p>Ao utilizar este site você aceita todos os termos do presente termo de responsabilidade. Se você não concordar com alguma item no presente termo você cancelar a opção a seguir e não utilizar o site eventualize.se.</p>


  <h2>Garantias e Responsabilidade</h2>
  <p>Este site tem por objetivo a visualização de informações sobre eventos cadastrados e organizados através do site Facebook.com. O conteúdo deste site é fornecido de boa fé, os organizadores do site www.eventualize.se garante que as informações serão mantidas até à data, são verdadeiras e não enganosas, ou que este site estará sempre disponível para uso. As interrupções devido a manutenções de conteúdo ou por problemas de serviços de suporte externos serão comunicadas aos usuários ativos do site por email. Este site não se responsabiliza pelas informações disponibilizadas no website Facebook.com.</p>
  <br />
  <p>Os serviços do site www.eventualize.se não oferecem riscos à contaminação por vírus e portanto determina que a responsabilidade do usuário tomar as disposições apropriadas para a proteção contra essas ameaças digitais.</p>
  <br />
  <p>Em nenhum caso o site www.eventualize.se se responsabiliza por quaisquer danos incidentais, indiretos, conseqüentes ou especiais de qualquer natureza, ou quaisquer danos, incluindo, sem limitação, aqueles resultantes de lucros cessantes, perda de contratos, a boa vontade de dados , informação, renda, poupanças antecipadas ou relações de negócio, ou não avisada da possibilidade de tais danos, decorrentes de ou em conexão com o uso deste website ou de quaisquer sites vinculados.</p>


  <h2>Exceções</h2>
  <p>Nada neste aviso aviso exclui ou limita a qualquer garantia implícita por lei para a morte, a fraude, de lesões corporais por negligência, ou qualquer outra coisa que não seria lícito ao www.eventualize.se para excluir.</p>


  <h2>Licença de utilização</h2>
  <p>Ao utilizar este site, você concorda com as exclusões e limitações de responsabilidade acima mencionados e aceitá-os como razoáveis. Não utilize este site se você não concordar que eles são razoáveis.</p>
  <br />
  <p>Se algum dos pontos deste termo de responsabilidade são encontrados para ser inexeqüível pela legislação aplicável, que não terá nenhuma influência sobre a exigibilidade do restante do aviso prévio aviso.</p>
  <br />
  <p>O material neste site, incluindo textos e imagens, está protegido por direitos de autor e é autor de www.eventualize.se , a menos creditado em contrário. Não pode ser copiado, reproduzido, republicado, baixado, publicado ou transmitido de qualquer forma, exceto quando autorizado pelos autores do site. O prévio consentimento por escrito do detentor dos direitos deve ser obtido para qualquer outro uso do material com os autores.</p>
  <br />
  <p>Nenhuma parte deste site pode ser distribuído ou copiado para qualquer finalidade comercial ou lucro financeiro.</p>
  <br />
  <p>Todos os direitos de propriedade intelectual em relação a este site são reservados e de propriedade de www.eventualize.se.</p>


  <h2>Links para outros sites e produtos</h2>
  <p>Links para outros websites são fornecidos para a conveniência dos usuários. Nós somos incapazes de fornecer qualquer garantia quanto à exatidão ou completude do conteúdo de tais sites, ou a confiabilidade, qualidade ou eficácia dos produtos fornecidos através de sites externos. Um link para um site externo não implica um endosso dos pontos de vista, informações ou produtos fornecidos ou detidas por tais websites.</p>


  <h2>Lei e Jurisdição</h2>
  <p>Este Termo de Responsabilidade será interpretado e regido pelo Direito Brasileiro, e qualquer disputa em relação a ele estão sujeitos à jurisdição dos tribunais do Brasil.</p>


  <h2>Variações</h2>
  <p>Nós nos reservamos o direito de rever e alterar este Termo de Responsabilidade ao longo do tempo e qualquer versão revista será considerada aplicável a partir da data da primeira publicação neste site e os usuários ativos serão comunicados por email.</p>


  <h2>Quem Somos</h2>
  <p>Este site é de propriedade da empresa Meganti Tecnologia da Informação LTDA.</p>
	
	<br />
	<br />
	<br />

</div>